### ISSUE TITLE
License hyperlink on anaconda.org not working

### ISSUE THREAD

**Issue by leofang** [conda-forge/cub-feedstock#13]
This hyperlink on anaconda.org does not correctly jump to `license_url` set in `meta.yaml`:
<img width="752" alt="截圖 2022-01-05 下午3 28 18" src="https://user-images.githubusercontent.com/5534781/148284664-7510f302-0d69-460d-93ba-1cf45e4723b4.png">

**Comment by jakirkham** [comment]
Thanks Leo! 😄

Looks like this recipe doesn't have `license_url`. Only seeing these `license*` fields:

https://github.com/conda-forge/cub-feedstock/blob/f6cf131f33cd927d40feb78d3c6fa01704331bff/recipe/meta.yaml#L27-L29

**Comment by leofang** [comment]
Misfired, sorry!

**Comment by jakirkham** [comment]
No worries. Though we could keep this open if we want to add it
